# ============================================================================
#  Render Blueprint para VitalSense API
# ----------------------------------------------------------------------------
databases:
  - name: vitalsense-db
    databaseName: vitalsense_db
    user: vitalsense
    plan: free

services:
  - type: web
    name: vitalsense-api
    runtime: docker
    dockerfilePath: ./Dockerfile
    plan: free
    healthCheckPath: /v3/api-docs

    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      
      # Forzar puerto 8080 para evitar fallos de escaneo en Render
      - key: PORT
        value: 8080

      # --- Conexion a la base de datos ---
      - key: DB_HOST
        fromDatabase:
          name: vitalsense-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: vitalsense-db
          property: port
      - key: DB_NAME
        fromDatabase:
          name: vitalsense-db
          property: database

      - key: DB_USERNAME
        fromDatabase:
          name: vitalsense-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: vitalsense-db
          property: password

      - key: CORS_ALLOWED_ORIGINS
        sync: false
