spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}
  application:
    name: vitalsense
  jpa:
    hibernate:
      ddl-auto: update
  ai:
    google:
      genai:
        api-key: ${GEMINI_API_KEY}
        chat:
          model: gemini-2.5-flash
        embedding:
          api-key: ${GEMINI_API_KEY}
          model: gemini-embedding-001
          dimensions: 768
          text:
            dimensions: 768
    vectorstore:
      pgvector:
        initialize-schema: true
        dimensions: 768
  logging:
    level:
      org.springframework.ai: DEBUG
      com.google.genai: DEBUG

server:
  port: ${PORT:8080}