package com.biotech.vitalsenseapi.doctor.model;

public enum Specialty {
    MEDICINA_GENERAL,
    CARDIOLOGIA,
    PEDIATRIA,
    DERMATOLOGIA,
    GINECOLOGIA_Y_OBSTETRICIA,
    OFTALMOLOGIA,
    TRAUMATOLOGIA_Y_ORTOPEDIA,
    PSIQUIATRIA,
    NEUROLOGIA,
    ENDOCRINOLOGIA,
    GASTROENTEROLOGIA,
    UROLOGIA,
    OTORRINOLARINGOLOGIA,
    ONCOLOGIA,
    ODONTOLOGIA
}
